function sessionData = createTestSessionData(targetDate)
    %CREATETESTSESSIONDATA Create a minimal valid SessionData struct
    %   sessionData = createTestSessionData() creates struct with default date
    %   sessionData = createTestSessionData(targetDate) creates struct with specified date

    if nargin < 1
        targetDate = datetime('2025-01-15');
    end

    sessionData = struct(...
        'version', '1.0.0', ...
        'appVersion', '1.0.0', ...
        'savedDate', datetime('now'), ...
        'targetDate', targetDate, ...
        'userNotes', 'Test session', ...
        'cases', [], ...
        'completedCases', [], ...
        'optimizedSchedule', struct(), ...
        'simulatedSchedule', struct(), ...
        'optimizationOutcome', struct(), ...
        'opts', struct(), ...
        'labIds', 1:6, ...
        'availableLabIds', 1:6, ...
        'lockedCaseIds', string.empty, ...
        'timeControlState', struct('isActive', false, 'currentTimeMinutes', NaN, ...
            'baselineLockedIds', string.empty, 'lockedCaseIds', string.empty), ...
        'operatorColors', struct('keys', {{}}, 'values', {{}}), ...
        'isOptimizationDirty', false, ...
        'historicalDataPath', '');
end
